import type { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  profile: {
    name: "Andre Rahmat",
    title: "Digital Marketing & Social Media Specialist",
    titleEn: "Digital Marketing & Social Media Specialist",
    tagline: "Membantu bisnis berkembang melalui media digital",
    taglineEn: "Helping businesses grow through digital media",
    about: "Saya adalah lulusan S1 Manajemen dengan pengalaman di bidang Digital Marketing, Content Creation, Meta Ads, dan Sosial Media Spesialist. Memiliki kemampuan dalam pembuatan konten, pengelolaan media sosial, serta menjalankan kampanye iklan digital untuk meningkatkan brand awareness. Saya senang mempelajari strategi pemasaran dan membantu bisnis berkembang melalui media digital.",
    aboutEn: "I am a Management graduate with experience in Digital Marketing, Content Creation, Meta Ads, and Social Media Specialization. I have skills in content creation, social media management, and running digital advertising campaigns to increase brand awareness. I enjoy learning marketing strategies and helping businesses grow through digital media.",
    education: "S1 Manajemen",
    educationEn: "Bachelor of Management",
    location: "Raharjo Lebosari Rt03/Rw07, Kec. Kangkung, Kab. Kendal",
    email: "andrerahmat1212@gmail.com",
  },
  social: {
    instagram: "https://www.instagram.com/andreproperty__",
    tiktok: "https://www.tiktok.com/@andreproperty__",
    googleDrive: "https://drive.google.com/drive/folders/127yBTp1emL7RhjAt-NETW3G9CPs8OnJa",
    cvDrive: "https://drive.google.com/drive/folders/127yBTp1emL7RhjAt-NETW3G9CPs8OnJa",
  },
  // TODO: UPDATE WITH REAL WHATSAPP NUMBER (format: 628xxxxxxxxxx)
  whatsapp: "6281234567890",
  experiences: [
    {
      id: "freelance-andre",
      role: "Freelance Digital Marketing Specialist",
      roleEn: "Freelance Digital Marketing Specialist",
      company: "Andre Property",
      period: "Mei 2026 - Sekarang",
      description: "Mengelola pemasaran digital melalui konten TikTok dan Instagram, mulai dari riset, pembuatan konsep, hingga publikasi konten.",
      descriptionEn: "Managing digital marketing through TikTok and Instagram content, from research, concept creation, to content publication.",
      achievements: [
        "Mengelola leads dan melakukan follow-up calon pembeli melalui WhatsApp untuk meningkatkan peluang closing",
        "Menganalisis performa konten untuk mengoptimalkan strategi digital marketing dan meningkatkan engagement",
      ],
      achievementsEn: [
        "Managing leads and following up with potential buyers via WhatsApp to increase closing opportunities",
        "Analyzing content performance to optimize digital marketing strategies and increase engagement",
      ],
      type: "relevant",
    },
    {
      id: "permata-sentul",
      role: "Digital Marketing Specialist",
      roleEn: "Digital Marketing Specialist",
      company: "PT Permata Sentul",
      period: "Sep 2025 - Apr 2026",
      description: "Melakukan pemasaran digital melalui Meta Ads & konten TikTok untuk meningkatkan leads dan konversi.",
      descriptionEn: "Performing digital marketing through Meta Ads & TikTok content to increase leads and conversions.",
      achievements: [
        "Mengelola dan melakukan follow-up leads dari berbagai channel (Meta Ads, TikTok, dan organic) hingga tahap konversi",
        "Menangani proses customer journey, termasuk edukasi produk dan administrasi awal",
        "Mendukung promosi melalui konten digital dan aktivitas pemasaran",
      ],
      achievementsEn: [
        "Managing and following up leads from various channels (Meta Ads, TikTok, and organic) through to conversion",
        "Handling customer journey process, including product education and initial administration",
        "Supporting promotion through digital content and marketing activities",
      ],
      type: "relevant",
    },
    {
      id: "tanatap-coffee",
      role: "Waiter",
      roleEn: "Waiter",
      company: "Tanatap Coffee",
      period: "Jan 2024 - Apr 2024",
      description: "Memberikan pelayanan langsung kepada pelanggan, termasuk menerima pesanan dan memastikan kualitas layanan untuk menciptakan pengalaman pelanggan yang baik.",
      descriptionEn: "Providing direct service to customers, including taking orders and ensuring service quality to create a good customer experience.",
      achievements: [],
      achievementsEn: [],
      type: "other",
    },
  ],
  skills: {
    hard: [
      "Social Media Management (TikTok & Instagram)",
      "Content Strategy & Planning",
      "Copywriting (Caption, Hook, Script)",
      "Digital Marketing Basic",
      "Paid Advertising (Meta Ads – Basic to Intermediate)",
      "Sales & Lead Generation",
      "Customer Engagement",
    ],
    soft: [
      "Communication Skills",
      "Creative Thinking",
      "Problem Solving",
      "Time Management",
      "Adaptability",
      "Teamwork",
      "Result-Oriented Mindset",
    ],
    tools: [
      "Canva",
      "CapCut",
      "Meta Business Suite",
      "Google Sheets / Excel",
      "WhatsApp Business",
    ],
  },
  portfolio: [
    {
      id: "tiktok-performance",
      title: "TikTok Content Performance",
      titleEn: "TikTok Content Performance",
      category: "Social Media",
      categoryEn: "Social Media",
      description: "Dokumentasi hasil performa beberapa konten TikTok yang saya kelola, berdasarkan data insight yang tersedia pada platform TikTok.",
      descriptionEn: "Documentation of performance results from TikTok content I managed, based on insight data available on the TikTok platform.",
      driveLink: "https://drive.google.com/drive/folders/127yBTp1emL7RhjAt-NETW3G9CPs8OnJa",
      image: "/portfolio/tiktok.jpg",
      sampleImageLabel: "TikTok Analytics Dashboard",
    },
    {
      id: "meta-ads-campaign",
      title: "Meta Ads Campaign Performance",
      titleEn: "Meta Ads Campaign Performance",
      category: "Paid Advertising",
      categoryEn: "Paid Advertising",
      description: "Iklan Meta Ads untuk lead generation dengan optimasi targeting dan konten kreatif.",
      descriptionEn: "Meta Ads campaigns for lead generation with targeting optimization and creative content.",
      driveLink: "https://drive.google.com/drive/folders/127yBTp1emL7RhjAt-NETW3G9CPs8OnJa",
      image: "/portfolio/meta-ads.jpg",
      sampleImageLabel: "Meta Ads Campaign Report",
    },
    {
      id: "kpi-performance",
      title: "KPI Performance Report",
      titleEn: "KPI Performance Report",
      category: "Analytics",
      categoryEn: "Analytics",
      description: "Monitoring pencapaian target kerja berdasarkan data.",
      descriptionEn: "Monitoring work target achievements based on data.",
      driveLink: "https://drive.google.com/drive/folders/127yBTp1emL7RhjAt-NETW3G9CPs8OnJa",
      image: "/portfolio/kpi.jpg",
      sampleImageLabel: "KPI Dashboard Report",
    },
  ],
  // TODO: UPDATE WITH REAL TESTIMONI FROM CLIENTS
  testimoni: [
    {
      id: "testimoni-1",
      name: "[Nama Klien]",
      role: "Klien",
      roleEn: "Client",
      message: "Testimoni dari klien akan ditampilkan di sini.",
      messageEn: "Testimonial from client will be displayed here.",
      isPlaceholder: true,
    },
    {
      id: "testimoni-2",
      name: "[Nama Klien]",
      role: "Klien",
      roleEn: "Client",
      message: "Testimoni dari klien akan ditampilkan di sini.",
      messageEn: "Testimonial from client will be displayed here.",
      isPlaceholder: true,
    },
    {
      id: "testimoni-3",
      name: "[Nama Atasan]",
      role: "Mantan Atasan",
      roleEn: "Former Supervisor",
      message: "Testimoni dari atasan akan ditampilkan di sini.",
      messageEn: "Testimonial from supervisor will be displayed here.",
      isPlaceholder: true,
    },
  ],
};
